"""
Report Agent
============
Generates structured incident reports from real RCA and AIOps agent outputs.
Context keys used:
  - rca_conclusion   : Final root cause text from the RCA agent
  - anomalies        : Anomaly list from the AIOps agent
  - incident_data    : Original incident payload from gateway
  - severity         : "critical" | "high" | "medium" | "low"
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from fastapi import FastAPI
from pydantic import BaseModel, Field
from shared.internal_auth import add_internal_auth_middleware
from shared.llm import get_llm_router

app = FastAPI(title="Report Agent")
add_internal_auth_middleware(app)
logger = logging.getLogger(__name__)
llm_router = get_llm_router()


class TaskRequest(BaseModel):
    instruction: str
    context: Dict[str, Any] = Field(default_factory=dict)


def _build_report_markdown(
    rca_conclusion: Optional[str],
    anomalies: Optional[list],
    incident_data: Optional[dict],
    severity: str,
    instruction: str,
) -> str:
    """Assemble a structured Markdown incident report from real agent outputs."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    # ── Anomaly section ────────────────────────────────────────────────────
    if anomalies:
        anomaly_lines = "\n".join(
            f"- **{a.get('metric', 'unknown')}**: {a.get('value', 'N/A')} "
            f"(threshold: {a.get('threshold', 'N/A')}, severity: {a.get('severity', 'N/A')})"
            for a in anomalies
        )
    else:
        anomaly_lines = "_No anomaly data available — AIOps agent was not invoked or returned no results._"

    # ── Root cause section ─────────────────────────────────────────────────
    rca_text = rca_conclusion or (
        "_Root cause analysis not yet completed — RCA agent was not invoked._"
    )

    # ── Incident metadata ──────────────────────────────────────────────────
    if incident_data:
        meta_lines = "\n".join(f"| {k} | {v} |" for k, v in incident_data.items())
        meta_section = "| Field | Value |\n|-------|-------|\n" + meta_lines
    else:
        meta_section = "_No incident metadata provided._"

    severity_badge = {
        "critical": "🔴 CRITICAL",
        "high": "🟠 HIGH",
        "medium": "🟡 MEDIUM",
        "low": "🟢 LOW",
    }.get(severity.lower(), "⚪ UNKNOWN")

    return f"""# Incident Report

**Generated:** {now}
**Severity:** {severity_badge}
**Request:** {instruction}

---

## 📊 Incident Details

{meta_section}

---

## ⚡ Detected Anomalies

{anomaly_lines}

---

## 🔍 Root Cause Analysis

{rca_text}

---

## ✅ Recommended Actions

Based on the analysis above:

1. Review the anomaly metrics listed and correlate with recent deployments.
2. Apply the root cause remediation described in the RCA conclusion.
3. Monitor metric recovery over the next 15 minutes.
4. Update the incident runbook with findings from this report.

---

*This report was auto-generated by the Multi-Agent AIOps Platform.*
"""


@app.post("/execute")
async def execute_task(req: TaskRequest):
    """Generate an incident report from real RCA + AIOps context."""
    logger.info("Report Agent received task: %s", req.instruction)

    ctx = req.context or {}

    # Extract outputs produced by upstream agents (passed via orchestrator context)
    rca_conclusion: Optional[str] = ctx.get("rca_conclusion") or ctx.get(
        "final_conclusion"
    )
    anomalies: Optional[list] = (
        ctx.get("anomalies")
        or ctx.get("detected_anomalies")
        or ctx.get("anomalies_detected")
    )
    incident_data: Optional[dict] = ctx.get("incident_data")
    severity: str = ctx.get("severity", "medium")

    report_md = _build_report_markdown(
        rca_conclusion=rca_conclusion,
        anomalies=anomalies,
        incident_data=incident_data,
        severity=severity,
        instruction=req.instruction,
    )

    # Use LLM to refine and generate the final report draft
    prompt = f"Refine the following incident report draft to make it professional and concise:\n\n{report_md}"
    try:
        report_md = await llm_router.chat(
            messages=[{"role": "user", "content": prompt}],
            task="report_draft",
            agent_name="report_agent"
        )
    except Exception as e:
        logger.error(f"Failed to refine report draft with LLM: {e}")

    # Minimal HTML conversion — for rich rendering in dashboards
    report_html = (
        "<pre style='font-family:monospace;white-space:pre-wrap'>"
        + report_md.replace("<", "&lt;").replace(">", "&gt;")
        + "</pre>"
    )

    return {
        "success": True,
        "message": "Incident report generated from real agent outputs.",
        "data": {
            "report_markdown": report_md,
            "report_html": report_html,
            "metadata": {
                "severity": severity,
                "has_rca": rca_conclusion is not None,
                "anomaly_count": len(anomalies) if anomalies else 0,
            },
        },
    }


@app.get("/health")
async def health():
    return {"status": "ok"}
